### ISSUE TITLE
ValueError: ndarray is not C-contiguous

### ISSUE THREAD

**Issue by dougalsutherland** [dougalsutherland/skl-groups#27]
```
Traceback (most recent call last):
  File "get_divs.py", line 27, in <module>
    divs[s_i, ti] = est.fit_transform(sub)
  File "/zfsauton/home/dsutherl/scratch/anaconda/lib/python2.7/site-packages/sklearn/base.py", line 426, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/zfsauton/home/dsutherl/scratch/anaconda/lib/python2.7/site-packages/skl_groups/divergences/knn.py", line 357, in transform
    self._flann_args(), self._n_jobs)
  File "/zfsauton/home/dsutherl/scratch/anaconda/lib/python2.7/site-packages/sklearn/externals/joblib/memory.py", line 281, in __call__
    return self.func(*args, **kwargs)
  File "/zfsauton/home/dsutherl/scratch/anaconda/lib/python2.7/site-packages/skl_groups/divergences/knn.py", line 483, in _est_divs
    n_jobs, min_dist, clamp)
  File "skl_groups_accel/knn_divs.pyx", line 221, in skl_groups_accel.knn_divs._estimate_cross_divs (skl_groups_accel/knn_divs.c:3781)
  File "stringsource", line 614, in View.MemoryView.memoryview_cwrapper (skl_groups_accel/knn_divs.c:17031)
  File "stringsource", line 321, in View.MemoryView.memoryview.__cinit__ (skl_groups_accel/knn_divs.c:13577)
ValueError: ndarray is not C-contiguous
```

**Comment by dougalsutherland** [comment]
Source came from `scipy.io.loadmat`.

**Comment by ChokJohn** [comment]
just use `<array.copy(order='C')>`
